### ISSUE TITLE
Different Codes from two Devices?

### ISSUE THREAD

**Issue by straussmaus** [google/google-authenticator-libpam#119]
This is a dumb question I guess but I am using this module and also an Android phone on the same website.  I entered the same key/code into both of these.  The time on both is the same.  But the generated codes are different.

Is that acceptable?  Can two codes be equally valid?  I expected them both to show the exact same code.

**Comment by ThomasHabets** [comment]
For TOTP (if you don't know if you're using HOTP or TOTP then you're very likely using TOTP, as HOTP is not time-based at all) the code is a direct function of *only* the current time, and the secret.

If you're getting different codes then either the secret is different, or the time on the phones are different, or both.


(there was one miscalculation a couple of years ago on Android due to some Java implementation not following ieee754, but that's been fixed for a long time now)

**Comment by straussmaus** [comment]
@ThomasHabets 

> If you're getting different codes then either the secret is different, or the time on the phones are different, or both.

Thank you for the answer.  I understand what you are saying.  But the time can be off by a little bit right?  And the little bit of difference will create a different code?  Or the formula that creates the code "rounds" the time?

I am wondering why the "off" code from my new implementation worked when usually I use the Android (Google Authenticator) and it works but the two had different codes.  From what you say I would think this was the one case where the time on my phone was off.  The only other explanation I have is that it is possible for two codes to be accepted?

**Comment by ThomasHabets** [comment]
@straussmaus The code changes every 30 seconds (the standard allows for other periods, but GA only implements 30s) on HH:MM:00 and HH:MM:30.

If the time is off on two phones by one second, but  have the same secret set, then phone1 will change to code `123456` one second before phone2 changes to `123456`. Often when there is time sync problems but the time appears the same the problem is that phones are incorrectly handling timezones, so it's not seconds off, but hours.

E.g. if you set your phone to the timezone of North Korea, and then set the time so that it *looks* like your local time, then you will get wrong codes. Then you've done two wrongs to make a right, and it breaks anything that time syncs.

The code between two periods will not look similar. Codes can not be predicted from other codes as it's a one-way function from (secret,time) to code.

That said, yes technically more than one code is accepted, because the PAM GA module will allow some codes before and after the current time, in case the clock is off. Maybe this is what you're seeing?

How many codes are accepted is configured with `google-authenticator`s option `-w`.
