### ISSUE TITLE
Stuck in a loop of `Password:` and failed login attempts

### ISSUE THREAD

**Issue by GGEZLOLLLLLLLLLLLLLLLLXD** [google/google-authenticator-libpam#178]
Whenever I attempt to login to any user, this happens:

```
$ ssh pi@192.168.86.254
Password: 
Password: 
Password: 
pi@192.168.86.254's password:
Permission denied, please try again.
pi@192.168.86.254's password: 
Received disconnect from 192.168.86.254 port 22:2: Too many authentication failures
Disconnected from 192.168.86.254 port 22
```

The `/etc/pam.d/sshd` config has the arguments:
`nullok echo_verification_code grace_period=300`

I'm basically locked out of all the accounts (some of which don't have 2fa activated) and have to manually get on to fix this.
Is it intended behavior or a bug?

**Comment by abhilesh** [comment]
I am in a similar situation and hoping someone can provide some clues about fixing this.

I am running 64-bit Raspberry Pi OS on a Raspberry Pi 4 running headless. 
Here are the steps I followed to add 2FA to my account

```
sudo apt install libpam-google-authenticator

google-authenticator

sudo cp /etc/pam.d/sshd !#$.dist
sudo nano /etc/pam.d/sshd
```

This is the edit I made in the /etc/pam.d/sshd (in order to be asked the verification code before the password)
```
auth required pam_google_authenticator.so

@include common-auth
```

Added the authenticator account to Authy. 

Now, we I try to ssh back into the pi from a local computer, I get stuck at the ```Permission denied, please try again``` loop.

```ssh pi@192.168.1X.X``` gives the following output where it gets stuck

```
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: password
pi@192.168.1.2's password:
debug1: Authentications that can continue: publickey,password
Permission denied, please try again.
pi@192.168.1.2's password:
debug1: Authentications that can continue: publickey,password
Permission denied, please try again.
pi@192.168.1.2's password:
```
I've tried using my old password, the default password, authy authentication code, scratch code and this stage but they all lead to the error.

I also don't know why it doesn't ask me about the verification code before the password as I have it configured in the ```/etc/pam.d/sshd``` file.

What steps should I try to fix the permission denied errors?

**Comment by ThomasHabets** [comment]
Different issue as you don't use grace period.

I'm locking this issue. File new with the extra info I asked for in my first comment on this issue. And see what extra info you see with `debug` option added.
