### ISSUE TITLE
Inconsistent window_size description in google-authenticator tool

### ISSUE THREAD

**Issue by ThomasHabets** [google/google-authenticator-libpam#4]
_From @pv2b on July 28, 2015 10:15_

When enrolling a new user into google-authenticator, using the google-authenticator tool, this question is asked:

By default, tokens are good for 30 seconds and in order to compensate for
possible time-skew between the client and the server, we allow an extra
token before and after the current time. If you experience problems with poor
time synchronization, you can increase the window from its default
size of 1:30min to about 4min. Do you want to do so (y/n)

I was curious as how this works, it turns out that if you choose "y", the following is dropped into the configuration file:

" WINDOW_SIZE 17

This would seem to mean that there are 17 concurrently valid codes, each of them valid for 30 seconds. That would mean a window of 17/2 minutes = 8m30s, a.k.a. +/- about 4 minutes.

If you choose "n", then nothing is written to the file, and the default in the PAM module is used, which is 3 (pam_google_authenticator.c - window_size function). This means a window of 3/2 minutes = 1m30s, a.k.a. +/- 30-60 seconds.

The problem is that the question above confuses window size with maximum acceptable time difference. The 1m30s referred to is a window size, and the ~4 minutes is a maximum acceptable time difference. The maximum acceptable time difference is approximately half the window size.

This could be resolved either by changing the descriptive text of the question, or by changing the behaviour to reduce the WINDOW_SIZE.

_Copied from original issue: google/google-authenticator#510_

**Comment by ThomasHabets** [comment]
_From @mikesoule on October 14, 2015 23:53_

+1 @pv2b Thanks for posting this!

**Comment by ThomasHabets** [comment]
_From @dene14 on March 7, 2016 23:34_

Additionally I would like to note that adding `--minimal-window` flag make WINDOW_SIZE value equal to "-1" which prevent any valid code from being accepted. Or please tell how it's supposed to work.

**Comment by ThomasHabets** [comment]
@dene14 that appears to be a bug. [This code](https://github.com/google/google-authenticator/blob/master/libpam/src/google-authenticator.c#L803) makes no sense since it only runs when `!use_totp`.

**Comment by ThomasHabets** [comment]
Sorry for the delay on this.

The new phrasing is:
```
By default, tokens are good for 30 seconds. In order to compensate for
possible time-skew between the client and the server, we allow an extra
token before and after the current time. If you experience problems with
poor time synchronization, you can increase the window from its default
size of +-1min (window size of 3) to about +-4min (window size of
17 acceptable tokens).
Do you want to do so? (y/n) 
```

Is that good enough? Suggestions welcome.

**Comment by pv2b** [comment]
Hi. The phrasing you suggested is still not accurate.

> By default, tokens are good for 30 seconds.

No, by default, the window size is 3, which means that any given token is valid during a time frame of 1 minute 30 seconds. From the perspective of the user, assuming perfect time sync between the server and client, a token is valid for 1 minute after it first appears on the screen of the mobile app, and 30 seconds after it's disappeared.

Better phrasing might be: "A new token is generated every 30 seconds by the mobile app."

In fact, how about this as a suggested phrasing?

A new token is generated every 30 seconds by the mobile app. In order to compensate for
possible time-skew between the client and the server, we allow an extra
token before and after the current time. This allows for a time skew of up to 30 seconds between authentication server and client. If you experience problems with
poor time synchronization, you can increase the window from its default
size 3 permitted code (one previous code, the current code, the next code) to 17 permitted codes (the 8 previous codes, the current code, and the 8 next codes). This will permit for a time skew of up to 4 minutes between client and server.

**Comment by ThomasHabets** [comment]
That sounds much clearer. I'll take care of it tomorrow.

**Comment by reedloden** [comment]
Perhaps keep the "by default" part, as the STEP_SIZE can be modified so that it's not just 30 seconds (some tokens are 60 seconds, for instance).
