### ISSUE TITLE
Non-root processes & Google Authentication System Capabilities

### ISSUE THREAD

**Issue by jonthegimp** [google/google-authenticator-libpam#73]
For processes that do not run with root privileges, such as MySQL, we've noticed that pam_google_authenticator.so will fail with a 'Failed to change user id to "<user>"'. The resolution to this being to allow the MySQL process to have setuid/setgid access via:

`setcap cap_setuid,cap_setgid+ep /sbin/mysqld`

The security concerns around this being that a compromised mysql process having access to setuid = root. 

Are there any other suggestions as to how to handle MFA with non-root processes using pam_google_authenticator.so?

**Comment by ThomasHabets** [comment]
You could set the `user=` option, so that the PAM module setuid's to itself.

Does that work for you?

**Comment by jonthegimp** [comment]
Thanks for the update, Thomas - would you mind explaining a little more how you see this working? From the brief trials I have had with setting the user= option, this option also requires setting the secret= option, which would seem to point to a specific users' .google_authenticator file.

**Comment by ThomasHabets** [comment]
Well, how do you mean that the auth should work? Have the mysql user be able to read the users secrets from their home dirs? Where should secrets be stored?

`secret=${HOME}/.google_authenticator` would be one option

**Comment by ThomasHabets** [comment]
Oh, and also `allowed_perm=0770` with proper group ownership.

**Comment by brandentimm** [comment]
The module still wants to switch to the authenticating user with the advised config changes.

In /etc/pam.d/mysql:
```
auth        required    pam_sss.so 
auth        required	  pam_google_authenticator.so debug secret=${HOME}/.google_authenticator allowed_perm=0770 no_strict_owner

account     [default=bad success=ok user_unknown=ignore] pam_sss.so
```
Perms and ownership of my google_authenticator file:
```
-bash-4.2$ ls -alh ~/.google_authenticator 
-rwxrwx--- 1 btimm mysql 106 Aug 29 12:29 /home/btimm/.google_authenticator
```
Relevant portion of /var/log/secure on login attempt:

```
Aug 29 12:36:42 mfa mysqld[3451]: pam_sss(mysql:auth): authentication success; logname= uid=<sanitized> euid=<sanitized> tty= ruser=btimm rhost=localhost user=btimm
Aug 29 12:36:42 mfa mysql(pam_google_authenticator)[3451]: debug: start of google_authenticator for "btimm"
Aug 29 12:36:42 mfa mysql(pam_google_authenticator)[3451]: Failed to change user id to "btimm"
```

I'm also seeing EPERM as the return of setresgid() from strace.

**Comment by ThomasHabets** [comment]
Also add `user=mysql` or whatever the user is.

**Comment by brandentimm** [comment]
We finally got this working, with a few more hiccups.  Just posting here for posterity:

First, we tried using the ${HOME} variable in secret=, e.g.

```
auth        required	  pam_google_authenticator.so debug user=mysql secret=${HOME}/.google_authenticator allowed_perm=0770 no_strict_owner
```

However it seems like that variable was not being correctly interpolated because /var/log/secure then reported:
`Aug 29 13:59:14 mfa mysql(pam_google_authenticator)[3451]: Failed to compute location of secret file for "
btimm"`

I noted that my username is preceded by a space in that error message, but I couldn't nail down exactly why that was.

We then changed it to use ${USER} instead, which allowed mysqld to read the .google_authenticator file, but the next error we hit was:

```
Aug 29 14:05:13 mfa mysql(pam_google_authenticator)[3451]: debug: "/home/btimm/.google_authenticator" read
Aug 29 14:05:13 mfa mysql(pam_google_authenticator)[3451]: debug: shared secret in "/home/btimm/.google_authenticator" processed
Aug 29 14:05:21 mfa mysql(pam_google_authenticator)[3451]: debug: no scratch code used from "/home/btimm/.google_authenticator"
Aug 29 14:05:21 mfa mysql(pam_google_authenticator)[3451]: Accepted google_authenticator for btimm
Aug 29 14:05:21 mfa mysql(pam_google_authenticator)[3451]: Failed to update secret file "/home/btimm/.google_authenticator": Permission denied
```

An strace revealed that mysqld was trying to write a temp file at $HOME/.google_authenticator~ (note the tilde on the end)

In order to give mysql acceptable permissions to write this temp file in order to update .google_authenticator, I created a new folder at $HOME/.google and placed .google_authenticator in that directory, then set mode 0770 with ownership <me>:mysql on the directory.

This finally allowed us to auth with the following PAM config:
`auth        required	  pam_google_authenticator.so debug user=mysql secret=/home/${USER}/.google/.google_authenticator allowed_perm=0770 no_strict_owner
`
The last piece was to get it working with SELinux.  I relabeled the .google folder like so:
`chcon -R -t mysqld_db_t ~/.google`

And finally we were able to successfully auth with no privilege escalation and SELinux enabled.

**Comment by brandentimm** [comment]
Another data point - in our case, `no_strict_owner` was not necessary since my authenticating user is also indeed the owner of .google_authenticator.

**Comment by ThomasHabets** [comment]
I don't know where the extra space came from, but I've now improved the log messages to say that `~` and `${HOME}` are not supported while `user` is set.

If you need this, file a separate issue.

**Comment by ThomasHabets** [comment]
Ah yes, I forgot about the write-rename needing write access to the directory the file is in.

I would recommend not using `no_strict_owner` if you don't have to, since the directory should normally be owned by the user.

**Comment by ThomasHabets** [comment]
By the way: Thank you for following up with the working version of the configuration.

**Comment by brandentimm** [comment]
You're welcome and thanks for pointing us in the right direction @ThomasHabets

**Comment by sreedhar100** [comment]
Had seen this forum. One question. With $USER we can ensure privilege is dropped to this user, however setgroup() will still fail as it tries setting the group of the authenticating user when the pam application does not run as root. Were you able to resolve this?
