### ISSUE TITLE
Not able to sync old account of Google authenticator

### ISSUE THREAD

**Issue by Vasutanwar** [google/google-authenticator-libpam#87]
I have change my phone and sync all apps though Google + . All apps are are synced to the new phone I just have to login again. My Google authenticator was linked to Bitfinex but I am not able to login on bitfinex as my Google authenticator is not synced and link with Bitfinex in new phone. Could you please help me to sync the Google authenticator with old account linked. Its very urgent

**Comment by ThomasHabets** [comment]
1) Are you the same person as "the-astronaut", who filed https://github.com/google/google-authenticator-android/issues/72? Similar broken English. Similar issue. This account was created just for this bug. If so then this is the third bug you file about the exact same issue and I have answered that question. **this is abuse**
2) This is not the project to file these issues, since it has nothing to do with the PAM module.

If you are not the same person as "the-astronaut", then I apologize for the accusation. Your question is very hard to read. Please file the bug with the right project, not forgetting to say at least:
1) What software you have
2) What hardware you have
3) What you have done
4) What you expected to happen
5) What actually happened

And be very specific. Maybe get someone you know who's more fluent in English to help you.
